import { Injectable } from '@angular/core';
import { HttpClient } from "@angular/common/http";

@Injectable({
  providedIn: 'root'
})
export class DataService {
  url = 'http://localhost:3000/';

  constructor(private response: HttpClient) { }

  getPrueba(variabales: JSON){
    return this.response.post(this.url+'test/getTest', variabales);
  }

  generateIns(variabales: JSON){
    return this.response.post(this.url+'generate/inserts', variabales);
  }

  autoGenerateIns(variabales: JSON){
    return this.response.post(this.url+'autogenerate/inserts', variabales);
  }

  generateDel(variabales: JSON){
    return this.response.post(this.url+'generate/delete', variabales);
  }

  autoGenerateDel(variabales: JSON){
    return this.response.post(this.url+'autogenerate/delete', variabales);
  }

  generateRet(variabales: JSON){
    return this.response.post(this.url+'generate/retrieve', variabales);
  }

  autoGenerateRet(variabales: JSON){
    return this.response.post(this.url+'autogenerate/retrieve', variabales);
  }
}

